### ISSUE TITLE
Error: Missing argument 'FILES...

### ISSUE THREAD

**Issue by JohnSmith2007** [boy1dr/SpleeterGui#134]
I have no clue of what it is that Spleeter is bitching about, but i need this to be taken care of as soon as humanly possible.
Any help is greatly appreciated.
![Screenshot (34)](https://user-images.githubusercontent.com/45465767/143681650-227ed282-e813-4d36-bbf9-66950f91a3b1.png)

**Comment by boy1dr** [comment]
Try putting the file on your desktop.
Spleeter doesn't like working in root directories


Sent from my mobile thingy
________________________________
From: JohnSmith2007 ***@***.***>
Sent: Saturday, November 27, 2021 10:39:31 PM
To: boy1dr/SpleeterGui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [boy1dr/SpleeterGui] Error: Missing argument 'FILES... (Issue #134)


I have no clue of what it is that Spleeter is bitching about, but i need this to be taken care of as soon as humanly possible.
Any help is greatly appreciated.
[Screenshot (34)]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F45465767%2F143681650-227ed282-e813-4d36-bbf9-66950f91a3b1.png&data=04%7C01%7C%7C28897011e81c4979481d08d9b1a2f625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736135737908758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VySq812kwSSTNnu0m65sqsPFGlRGZddXjBKPqlAGNzg%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fboy1dr%2FSpleeterGui%2Fissues%2F134&data=04%7C01%7C%7C28897011e81c4979481d08d9b1a2f625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736135737908758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FvhbGNUq06tBLFxHFmPKRVvYk%2Bicf3%2FzlAQsDEsRIak%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABHZXJBTDG6TYOI4IET2QPLUODGQHANCNFSM5I4EYQCA&data=04%7C01%7C%7C28897011e81c4979481d08d9b1a2f625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736135737908758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j8LPVDNA01IEz9KNSkngoVqdoKO7TovvhI1PoQqlax0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C28897011e81c4979481d08d9b1a2f625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736135737918713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g8Faec4szu0nn6uY0IOpnMJxpmCU423uufZCa304OQc%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C28897011e81c4979481d08d9b1a2f625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736135737918713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ok22MKSzvk%2BlCTRu2OcQCJJ2hBHMUiDAYDeGS2361p8%3D&reserved=0>.

**Comment by JohnSmith2007** [comment]
@boy1dr Ok, that got rid of the error. But now it's not processing anything. It'll complete the process, but there aren't any files in the output folder.

**Comment by EnderOcelot** [comment]
it lost the file called  _main_.py，you shoud fix this bugs,am wait the next version

**Comment by EnderOcelot** [comment]
@boy1dr it lost file called _main_.py,you should fix this.am waiting gui next version

**Comment by ZetaSp** [comment]
Don't set the output directory to disk root like `D:\`, try something like `D:\Songs\`.
This worked for me.

**Comment by boy1dr** [comment]
There has been some issues with the last few updates from Spleeter, i have managed to get python stable again.
The latest installer 2.9.2 can be found here https://makenweb.com/SpleeterGUI
