### ISSUE TITLE
Spleeting is goodish but there is no FLAC option for output

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [boy1dr/SpleeterGui#153]
I am using the 16Khz option in the GUI
But I was using that before in the config file using command prompt and didn't get results like those by the GUI
What kind of syntaxs did you use on spleeter command?
What version of FFMpeg did you use? 
How can I make the GUI export to FLAC instead of WAV?

**Comment by boy1dr** [comment]
Hi
WAV is a true lossless format, WAV has no compression, it is basically analog audio in a digital form. there are no plans to change this in the future. This is because there are artifacts generated by the separation process that do not encode well with codecs. it is always best to work with unencoded audio as often as possible.

There is a config file i use in the GUI where you can change whatever you like about the separation process. This can be found in your appdata folder.
Mine is located here...  C:\Users\mitch\AppData\Roaming\SpleeterGUI\config.json

**Comment by MohammedMehdiTBER** [comment]
> Hi WAV is a true lossless format, WAV has no compression, it is basically analog audio in a digital form. there are no plans to change this in the future. This is because there are artifacts generated by the separation process that do not encode well with codecs. it is always best to work with unencoded audio as often as possible.
> 
> There is a config file i use in the GUI where you can change whatever you like about the separation process. This can be found in your appdata folder. Mine is located here... C:\Users\mitch\AppData\Roaming\SpleeterGUI\config.json

I just tried to use wave codec option on CLI and It didn't produce the same quality as your GUI presettings.
It seems that you are using an old special version of FFmpeg or something different in the config other than that 16Khz setting.
Please tell me, may Allah bless you, what are all the tweaks you have done to the spleeting process!
