### ISSUE TITLE
Website installer does not work

### ISSUE THREAD

**Issue by nebulaclone** [boy1dr/SpleeterGui#19]
I tried downloading the installer from Makenweb and get the following error message:-

This site can’t be reached
The web page at https://1drv.ms/u/s!AhbM98WiPUJYmTA106RumxHrovS7?e=HgF2ah might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by dankwartrustow** [comment]
The package is available. You could try a wget or change your IP address and try again. It’s possible your IP address was part of a block from a VPN, or otherwise blacklisted/throttled. From: nebulacloneSent: Wednesday, May 13, 2020 6:27 AMTo: boy1dr/SpleeterGuiCc: SubscribedSubject: [boy1dr/SpleeterGui] Website installer does not work (#19) I tried downloading the installer from Makenweb and get the following error message:-This site can’t be reachedThe web page at https://1drv.ms/u/s!AhbM98WiPUJYmTA106RumxHrovS7?e=HgF2ah might be temporarily down or it may have moved permanently to a new web address.ERR_TUNNEL_CONNECTION_FAILED—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by boy1dr** [comment]
The file is stored in MS onedrive, i just checked the link on a signed out browser and it's working fine here in Australia.
A quick google of ERR_TUNNEL_CONNECTION_FAILED suggests there's an issue with your internet connection. Possibly Proxy or VPN trouble.

**Comment by nebulaclone** [comment]
Thanks for the assistance. I had to take a long winded approach, but managed to download the installer in the end. Great utility by the way!
