### ISSUE TITLE
GUI elements for training Models?

### ISSUE THREAD

**Issue by JavaShipped** [boy1dr/SpleeterGui#20]
Love this project, probably one of the best GUI projects for spleeter, but I'm not entering the world of training my own model using spleeter. Is there functionality already baked in for the training functions of spleeter? If not is there any plans to do so?

Again, really awesome GUI, super simple and easy to understand, which was key for some of my friends when I recommended spleeter! Powershell can be very daunting.

**Comment by boy1dr** [comment]
Thanks for the kind words :)
Spleeter has a great wiki https://github.com/deezer/spleeter/wiki/2.-Getting-started#train-model
I haven't tried it myself but it doesn't look too hard. the MusDB dataset is quite large and the training takes a powerful computer quite a while, But i'm guessing you have your own stems to train on so i wouldn't know how long it would take.
Best of luck :)

**Comment by 186cx342ds3422** [comment]
I also love this project and would be interested in the ability to use the Train and Evaluate functionality provided by spleeter through the GUI. Getting this to function by using Spleeter directly is a bit cumbersome and would be much easier if it could be included within the GUI.

I've done some reading on this and It seems Spleeter can utilize either the CPU and or Graphics Card (Preferable) for both of these features. Access to the MusdDB collection is just a simple request to the owner and then one can pull down the entries set. Also it looks like there is the ability to create your own stems via the Native Instruments Stem Creator which will take pre-created stems of a project along with a master and combined them into the *.stem.mp4 file needed for Training and Evaluation.

**Comment by boy1dr** [comment]
@186cx342ds3422 i would like to add this as a feature but since i haven't tried it myself i don't currently know how to do it. So this weekend i will have a crack at it and see if it's something that can go in to the next release :)
In the meantime if you would like to activate the GPU version of spleeter i have prepared some details on how to do it here https://makenweb.com/spleeter_help.php it's not for the faint-hearted.
From what i have read it would be almost a requirement to be using GPU for training, Especially if you use MusDB & your own stem sources as well. we're talking 22GB + your own stem data.
But keep in mind that depending on what music you want to separate using MusDB might not be all that useful (if it's not been all that successful for you thus far).

**Comment by Gusher** [comment]
Also would like to see  NVidia CUDA gpu setting options on the frontend....

**Comment by boy1dr** [comment]
@Gusher it wouldn't be hard to provide an option to switch between spleeter-cpu and spoleeter-gpu.
The real problem is the NVidia driver setup which is explained here https://makenweb.com/spleeter_help.php
It's not something that i can provide on the frontend :(

**Comment by Gusher** [comment]
..you can prolly add code that automatically detects whether it's installed or not and if it is the option to select it becomes highlighted from greyed out... it is a fancy option that maybe you might want to save later for a payed version...

**Comment by boy1dr** [comment]
spleeter does this by itself now
