### ISSUE TITLE
<Saved path>\<song name>\vocals.wav: No such file or directory

### ISSUE THREAD

**Issue by cantabileteki** [boy1dr/SpleeterGui#213]
Hello, I met an error "No such file or directory" for the saved path:

 libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
E:\\spleeterMusic\passionate_land\vocals.wav: No such file or directory

I also tried with "E:\spleeterMusic", just typing one "\\", same problem happend.

Thanks

**Comment by boy1dr** [comment]
Spleeter can be picky about file permissions and locations.
It doesn't seem to like root directories like e:\output and check the permissions on the folder.

Your antivirus and/or antimalware service might be prohibiting access to that location. you may need to whitelist the SpleeterGUI app and any folders you intend on using with SpleeterGUI.
This happens because apps like defender don't like unsigned exe applications running python scripts that read and write to files.
Sorry about the late reply.
