### ISSUE TITLE
Do not show the spleeter email address in the console logs

### ISSUE THREAD

**Issue by mmoussallam** [boy1dr/SpleeterGui#38]
Hi there!

I'm writing to you on behalf of the `spleeter` dev team. First, we think that spleeterGUI is very cool, congrats for that.

However since you do a `pip show spleeter` at the start of the program, the email address research -at- deezer -dot- com is shown at startup (and also on the screenshot used in https://makenweb.com/spleeter2.php ) which unfortunately lead some of your users to contact us when they encounter an issue :) and it's most of the time not related to `spleeter` itself. 

Would it be possible to perhaps add some pointers to your github repo before this call so that your users will know right away where to look for help ?

Thanks in advance and have a nice week-end!

**Comment by boy1dr** [comment]
Hi :)
Thanks for the kind words!

Apologies i never intended for that to happen, i only do the pip show command so users could see which version of spleeter they are running. Is there an alternative command i can use to display the spleeter version?
Otherwise i'll strip the email address out.
I'll also make my details more prominent. I had thought maybe your people would be upset if i made it look too much like spleeter was my creation.

**Comment by boy1dr** [comment]
all good, i found a way
python -m pip list | findstr /R /C:"spleeter"

Thanks to you and your team for spleeter, it's an amazing piece of software.

**Comment by mmoussallam** [comment]
Great! Thanks a lot !
