### ISSUE TITLE
ffmpeg error ? 

### ISSUE THREAD

**Issue by inv3rtebrate** [boy1dr/SpleeterGui#62]
Starting processing of all songs
Processing C:\Users\Miles\Desktop\12 - Three 6 Mafia - Tounge Ring.mp3
ERROR:spleeter:FFMPEG error: b"ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20191010\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 35.101 / 56. 35.101\r\n  libavcodec     58. 60.100 / 58. 60.100\r\n  libavformat    58. 33.100 / 58. 33.100\r\n  libavdevice    58.  9.100 / 58.  9.100\r\n  libavfilter     7. 66.100 /  7. 66.100\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nGuessed Channel Layout for Input Stream #0.0 : stereo\r\nInput #0, f32le, from 'pipe:':\r\n  Duration: N/A, bitrate: 2822 kb/s\r\n    Stream #0:0: Audio: pcm_f32le, 44100 Hz, stereo, flt, 2822 kb/s\r\nC:\\Users\\Miles\\Desktop\\spleeter\\12 - Three 6 Mafia - Tounge Ring/accompaniment.wav: Permission denied\r\n"
Finished processing all songs

Run complete

This is the log I get, all there is created is a folder with no files. Any help for this? I don't understand much in codes but I see permission denied at end of it maybe helps? thanks in advance.
First time trying the app didn't get it to work yet but I'm so excited to give it a try!

PS: My computer specs are i5-8600k / 24gb ram / rtx-2070

**Comment by boy1dr** [comment]
@inv3rtebrate  your computer is certainly up to the task.
This is puzzling because it is saying that it was unable to write the first file
C:\Users\Miles\Desktop\spleeter\12 - Three 6 Mafia - Tounge Ring/accompaniment.wav
This would normally mean that the folder is write protected but i'm going to guess that you created the "spleeter" folder on your desktop and that would mean that you should be able to write to it.
The only thing that comes to mind is Windows 10 with it's ransomware protection enabled can prevent some applications from writing to or changing files on your system.
Is it possible ransomware protection is enabled?

**Comment by inv3rtebrate** [comment]
@boy1dr I've got avast installed and I didn't add any exception or such, not very related to how to do it, I'm gonna disable avast and try again to see if anything changes
