### ISSUE TITLE
help with python

### ISSUE THREAD

**Issue by leonroberts1972** [boy1dr/SpleeterGui#75]
when i open the programme, it says cant find python.exe
it in the folder windowsapp, but when i look for it through spleeter, i can't access it
this is stopping the software from working, any ideas please

**Comment by boy1dr** [comment]
try uninstalling it and re-installing. seems like something went wrong during the install process.

**Comment by crillev** [comment]
I just tried to install 2.9 and now have the same problem (can't find python.exe).
Version 2.8 worked like a charm.
Have I missed something, do I need to install Python separately?

**Comment by boy1dr** [comment]
2.9 is a 64bit application, otherwise it's the same package.

I will give you an upgrade command to run from your command line, this should get everything up to date. replace YOURNAME with your user account
C:\Users\YOURNAME\AppData\Roaming\SpleeterGUI\python\python.exe -m pip install --upgrade spleeter

as for why it can't find python.exe i don't know. it is at the location mentioned above. perhaps antivirus has blocked/deleted it.
MS defender often quarantines python.exe and the spleeter package, you might need to exclude that folder if that is the case.

check here for more help https://makenweb.com/spleeter_help.php
