### ISSUE TITLE
No output files on Windows 8.1

### ISSUE THREAD

**Issue by negative1ne** [boy1dr/SpleeterGui#80]
Ran it multiple times, and says its processing files.
Tried it with mp3 and wav files.

Picked options, and then output folder.
Then selected file.

No output files result.

Log
===========================================================
Starting processing of all songs
Processing C:\data\mus\mp3\alphabetical\d\DMBX2 2004\0201.wav
Finished processing all songs

Run complete
===========================================================
Installation completed with no errors.
Gui 2.9 version

**Comment by negative1ne** [comment]
Follow up.

Was a low memory error. I have 8Gb of RAM

How do I set up an enviroment variable to give Python more memory.

I have plenty of disk space also.

**Comment by boy1dr** [comment]
The 5 minute song length limit was put in place because of the exponential memory usage of Spleeter the longer the track is.
For folks that have the system resources the option is there to extend the processing.

**Comment by negative1ne** [comment]
thanks for the information. i can use the 2 track processing on much longer tracks
successfully though. i am using the high quality option. wonder if i deselect that,
would it help with memory requirements.

**Comment by negative1ne** [comment]
Thanks for fixing this.
Do you know when the changes will be implemented.

The GUI and version have not changed from 2.9 in the download links.

Thanks.

**Comment by boy1dr** [comment]
Sorry there's no "fix" for this that i am aware of. Spleeter can use an insane amount of memory, especially if it is given a long tack to work on and choose the 4 or 5 stem model.
My last comment was "For folks that have the system resources the option is there to extend the processing.". 
the thread was closed due to inactivity. 
My system has 32GB ram and my pagefile settings extend that by another 48GB if required.

Feel free to go in to more detail if i have misunderstood the problem you are having.
