### ISSUE TITLE
Unable to find python.exe

### ISSUE THREAD

**Issue by Halcyon9453** [boy1dr/SpleeterGui#93]
I've test both inbuilt python and custom install python, Spleeter still couldn't find python.exe. However once I downgrade the version from **2.9 to 2.7**, it somehow just work.

**Comment by boy1dr** [comment]
The big change in V2.8 was switching to a 64bit app, maybe your pc only wants to run 32bit apps?
Also, you will need to use the python that comes packed with my app since it has a few extra files that it needs to run. I provided the option to specify python location in case you wanted to move the install to a different drive.

And don't run the spleeter core upgrade unless you are using the latest version of SpleeterGUI ;)
